# .github/workflows/citation.yaml
name: Update CITATION.cff

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true        # never run two updates in parallel

jobs:
  update-citation:
    runs-on: ubuntu-latest
    permissions:
      contents: write             # needed for committing back to the repo

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0          # ensure tags are present for release info

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: .github/scripts/update_citation.py

    - name: Install deps
      run: python -m pip install --upgrade pip requests pyyaml

    - name: Regenerate CITATION.cff
      run: python .github/scripts/update_citation.py

    - name: Commit and push if changed
      run: |
        if git diff --quiet CITATION.cff; then
          echo "No changes – skipping commit."
        else
          git config user.email "actions@github.com"
          git config user.name  "GitHub Actions"
          git add CITATION.cff
          git commit -m "chore(citation): refresh after ${{ github.event.release.tag_name }}"
          git push
        fi
