name: Publish to PyPI

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi-repository
    permissions:
      contents: read      # checkout
      id-token: write     # OIDC for Trusted Publishing

    steps:
    - uses: actions/checkout@v4.1.2

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: |
        python -m pip install --upgrade pip build
        python -m build --sdist --wheel

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
