---
name: Test

on:    # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:  # allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test

    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .  # current package in editable mode

      - name: Test with pytest
        run: |
          pytest tests/test_back.py
          pytest tests/test_tools.py
          pytest tests/test_masks.py
          pytest tests/test_basic_beam_size.py
          pytest tests/test_noise.py
          pytest tests/test_no_noise.py
          pytest tests/test_iso_noise.py
