# .github/workflows/test.yaml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:                       # cancel stale CI runs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python ${{ matrix.python-version }} – ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.12"]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip                       # built-in cache for wheels
        cache-dependency-path: |
          pyproject.toml

    - name: Install package (+tests)
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .
        python -m pip install pytest

    - name: Run pytest
      run: |
        pytest -q
