# .github/workflows/test.yaml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:                       # cancel stale CI runs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python ${{ matrix.python-version }} – ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]   # drop 3.7 (EoL)

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip                       # built-in cache for wheels
        cache-dependency-path: |
          pyproject.toml
          requirements*.txt

    - name: Install package (+tests)
      run: |
        python -m pip install --upgrade pip
        # if you use extras: python -m pip install -e .[test]
        python -m pip install -e .
        python -m pip install -r requirements.txt
        python -m pip install pytest pytest-cov

    - name: Run pytest
      run: |
        pytest -q --cov=laserbeamsize --cov-report=xml

    - name: Upload coverage to summary
      if: always()
      run: |
        coverage=$(awk '/^TOTAL/{print $4}' coverage.xml)
        echo "### Test coverage: **${coverage%?}%**" >> $GITHUB_STEP_SUMMARY

    - uses: actions/upload-artifact@v4     # optional: keep the XML
      if: always()
      with:
        name: coverage-${{ matrix.python-version }}
        path: coverage.xml
